# Generated by Django 4.2.5 on 2023-09-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(default='전체', max_length=255)),
                ('temporary', models.BooleanField(default='Y', max_length=1)),
                ('views', models.PositiveIntegerField(default=0)),
                ('author_id', models.CharField(max_length=50)),
            ],
        ),
    ]
