# Generated by Django 4.2.5 on 2023-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_topic_blogpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='temporary',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='publish',
            field=models.BooleanField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(default='전체', max_length=255),
        ),
    ]
