# Generated by Django 4.2.5 on 2023-09-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_rename_topic_blogpost_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='temporary',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
