# Generated by Django 4.2.5 on 2023-09-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0005_alter_blogpost_temporary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="temporary",
            new_name="public",
        ),
    ]
