# Generated by Django 4.2.5 on 2023-09-16 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0006_rename_temporary_blogpost_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="public",
            new_name="publish",
        ),
    ]
