# Generated by Django 4.2.5 on 2023-09-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_project_account',
            new_name='project_account',
        ),
    ]
