# Generated by Django 4.2.5 on 2023-09-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_project_account_project_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project_account',
            new_name='blog_project_account',
        ),
    ]
